# Generated by Django 5.2.11 on 2026-02-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
