# Generated by Django 5.2.11 on 2026-02-20 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaxSupportNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('storage', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('release_date', models.DateField()),
                ('max_battery', models.IntegerField()),
                ('main_camera_res', models.FloatField()),
                ('selfie_camera_res', models.FloatField()),
                ('has_nfc', models.BooleanField(default=False)),
                ('has_headphone_jack', models.BooleanField(default=True)),
                ('product_image', models.URLField(max_length=250)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('max_supported_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.maxsupportnetwork')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.operatingsystem')),
            ],
        ),
    ]
