# Generated by Django 5.2.11 on 2026-02-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='synopsis',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
